import './App.css';

import { ReactPhotoCollage } from "react-photo-collage";

const BASE_URL = "https://grahampatterson.dev/weddingphotos";
const PHOTO_LIST = [
  { source: `${BASE_URL}/_DSF6102.JPG` },
  { source: `${BASE_URL}/_DSF6072.JPG` },
  { source: `${BASE_URL}/_DSF6073.JPG` },
  { source: `${BASE_URL}/_DSF6074.JPG` },
  { source: `${BASE_URL}/_DSF6075.JPG` },
  { source: `${BASE_URL}/_DSF6076.JPG` },
  { source: `${BASE_URL}/_DSF6077.JPG` },
  { source: `${BASE_URL}/_DSF6078.JPG` },
  { source: `${BASE_URL}/_DSF6079.JPG` },
  { source: `${BASE_URL}/_DSF6080.JPG` },
  { source: `${BASE_URL}/_DSF6081.JPG` },
  { source: `${BASE_URL}/_DSF6082.JPG` },
  { source: `${BASE_URL}/_DSF6083.JPG` },
  { source: `${BASE_URL}/_DSF6084.JPG` },
  { source: `${BASE_URL}/_DSF6085.JPG` },
  { source: `${BASE_URL}/_DSF6087.JPG` },
  { source: `${BASE_URL}/_DSF6088.JPG` },
  { source: `${BASE_URL}/_DSF6089.JPG` },
  { source: `${BASE_URL}/_DSF6090.JPG` },
  { source: `${BASE_URL}/_DSF6091.JPG` },
  { source: `${BASE_URL}/_DSF6092.JPG` },
  { source: `${BASE_URL}/_DSF6093.JPG` },
  { source: `${BASE_URL}/_DSF6094.JPG` },
  { source: `${BASE_URL}/_DSF6095.JPG` },
  { source: `${BASE_URL}/_DSF6096.JPG` },
  { source: `${BASE_URL}/_DSF6097.JPG` },
  { source: `${BASE_URL}/_DSF6098.JPG` },
  { source: `${BASE_URL}/_DSF6099.JPG` },
  { source: `${BASE_URL}/_DSF6026.JPG` },
  { source: `${BASE_URL}/_DSF6029.JPG` },
  { source: `${BASE_URL}/_DSF6032.JPG` },
  { source: `${BASE_URL}/_DSF6049.JPG` },
  { source: `${BASE_URL}/_DSF6050.JPG` },
  { source: `${BASE_URL}/_DSF6051.JPG` },
  { source: `${BASE_URL}/_DSF6053.JPG` },
  { source: `${BASE_URL}/_DSF6054.JPG` },
  { source: `${BASE_URL}/_DSF6058.JPG` },
  { source: `${BASE_URL}/_DSF6059.JPG` },
  { source: `${BASE_URL}/_DSF6060.JPG` },
  { source: `${BASE_URL}/_DSF6061.JPG` },
  { source: `${BASE_URL}/_DSF6062.JPG` },
  { source: `${BASE_URL}/_DSF6063.JPG` },
  { source: `${BASE_URL}/_DSF6065.JPG` },
  { source: `${BASE_URL}/_DSF6066.JPG` },
  { source: `${BASE_URL}/_DSF6067.JPG` },
  { source: `${BASE_URL}/_DSF6068.JPG` },
  { source: `${BASE_URL}/_DSF6070.JPG` },
  { source: `${BASE_URL}/_DSF6071.JPG` },
  { source: `${BASE_URL}/_DSF6100.JPG` },
  { source: `${BASE_URL}/_DSF6101.JPG` },
  { source: `${BASE_URL}/_DSF6103.JPG` },
  { source: `${BASE_URL}/_DSF6104.JPG` },
  { source: `${BASE_URL}/_DSF6106.JPG` },
  { source: `${BASE_URL}/_DSF6107.JPG` },
  { source: `${BASE_URL}/_DSF6108.JPG` },
  { source: `${BASE_URL}/_DSF6110.JPG` },
  { source: `${BASE_URL}/_DSF6111.JPG` },
  { source: `${BASE_URL}/_DSF6112.JPG` },
  { source: `${BASE_URL}/_DSF6113.JPG` },
  { source: `${BASE_URL}/_DSF6114.JPG` },
  { source: `${BASE_URL}/_DSF6115.JPG` },
  { source: `${BASE_URL}/_DSF6116.JPG` },
  { source: `${BASE_URL}/_DSF6117.JPG` },
  { source: `${BASE_URL}/_DSF6118.JPG` },
  { source: `${BASE_URL}/_DSF6119.JPG` },
  { source: `${BASE_URL}/_DSF6120.JPG` },
  { source: `${BASE_URL}/_DSF6122.JPG` },
  { source: `${BASE_URL}/_DSF6123.JPG` },
  { source: `${BASE_URL}/_DSF6124.JPG` },
  { source: `${BASE_URL}/_DSF6125.JPG` },
  { source: `${BASE_URL}/_DSF6126.JPG` },
  { source: `${BASE_URL}/_DSF6127.JPG` },
  { source: `${BASE_URL}/_DSF6128.JPG` },
  { source: `${BASE_URL}/_DSF6129.JPG` },
  { source: `${BASE_URL}/_DSF6130.JPG` },
  { source: `${BASE_URL}/_DSF6131.JPG` },
  { source: `${BASE_URL}/_DSF6132.JPG` },
  { source: `${BASE_URL}/_DSF6133.JPG` },
  { source: `${BASE_URL}/_DSF6135.JPG` },
  { source: `${BASE_URL}/_DSF6136.JPG` },
  { source: `${BASE_URL}/_DSF6137.JPG` },
  { source: `${BASE_URL}/_DSF6138.JPG` },
  { source: `${BASE_URL}/_DSF6139.JPG` },
  { source: `${BASE_URL}/_DSF6140.JPG` },
  { source: `${BASE_URL}/_DSF6141.JPG` },
  { source: `${BASE_URL}/_DSF6142.JPG` },
  { source: `${BASE_URL}/_DSF6143.JPG` },
  { source: `${BASE_URL}/_DSF6144.JPG` },
  { source: `${BASE_URL}/_DSF6145.JPG` },
  { source: `${BASE_URL}/_DSF6146.JPG` },
  { source: `${BASE_URL}/_DSF6147.JPG` },
  { source: `${BASE_URL}/_DSF6148.JPG` },
  { source: `${BASE_URL}/_DSF6149.JPG` },
  { source: `${BASE_URL}/_DSF6151.JPG` },
  { source: `${BASE_URL}/_DSF6152.JPG` },
  { source: `${BASE_URL}/_DSF6154.JPG` },
  { source: `${BASE_URL}/_DSF6155.JPG` },
  { source: `${BASE_URL}/_DSF6157.JPG` },
  { source: `${BASE_URL}/_DSF6158.JPG` },
  { source: `${BASE_URL}/_DSF6159.JPG` },
  { source: `${BASE_URL}/_DSF6161.JPG` },
  { source: `${BASE_URL}/_DSF6162.JPG` },
  { source: `${BASE_URL}/_DSF6163.JPG` },
  { source: `${BASE_URL}/_DSF6164.JPG` },
  { source: `${BASE_URL}/_DSF6165.JPG` },
  { source: `${BASE_URL}/_DSF6166.JPG` },
  { source: `${BASE_URL}/_DSF6167.JPG` },
  { source: `${BASE_URL}/_DSF6168.JPG` },
  { source: `${BASE_URL}/_DSF6169.JPG` },
  { source: `${BASE_URL}/_DSF6170.JPG` },
  { source: `${BASE_URL}/_DSF6171.JPG` },
  { source: `${BASE_URL}/_DSF6172.JPG` },
  { source: `${BASE_URL}/_DSF6173.JPG` },
  { source: `${BASE_URL}/_DSF6174.JPG` },
  { source: `${BASE_URL}/_DSF6175.JPG` },
  { source: `${BASE_URL}/_DSF6176.JPG` },
  { source: `${BASE_URL}/_DSF6177.JPG` },
  { source: `${BASE_URL}/_DSF6178.JPG` },
  { source: `${BASE_URL}/_DSF6181.JPG` },
  { source: `${BASE_URL}/_DSF6182.JPG` },
  { source: `${BASE_URL}/_DSF6183.JPG` },
  { source: `${BASE_URL}/_DSF6184.JPG` },
  { source: `${BASE_URL}/_DSF6186.JPG` },
  { source: `${BASE_URL}/_DSF6187.JPG` },
  { source: `${BASE_URL}/_DSF6188.JPG` },
  { source: `${BASE_URL}/_DSF6189.JPG` },
  { source: `${BASE_URL}/_DSF6190.JPG` },
  { source: `${BASE_URL}/_DSF6191.JPG` },
  { source: `${BASE_URL}/_DSF6192.JPG` },
  { source: `${BASE_URL}/_DSF6193.JPG` },
  { source: `${BASE_URL}/_DSF6194.JPG` },
  { source: `${BASE_URL}/_DSF6196.JPG` },
  { source: `${BASE_URL}/_DSF6197.JPG` },
  { source: `${BASE_URL}/_DSF6198.JPG` },
  { source: `${BASE_URL}/_DSF6199.JPG` },
  { source: `${BASE_URL}/_DSF6200.JPG` },
  { source: `${BASE_URL}/_DSF6201.JPG` },
  { source: `${BASE_URL}/_DSF6202.JPG` },
  { source: `${BASE_URL}/_DSF6203.JPG` },
  { source: `${BASE_URL}/_DSF6204.JPG` },
  { source: `${BASE_URL}/_DSF6205.JPG` },
  { source: `${BASE_URL}/_DSF6206.JPG` },
  { source: `${BASE_URL}/_DSF6207.JPG` },
  { source: `${BASE_URL}/_DSF6208.JPG` },
  { source: `${BASE_URL}/_DSF6209.JPG` },
  { source: `${BASE_URL}/_DSF6211.JPG` },
  { source: `${BASE_URL}/_DSF6212.JPG` },
  { source: `${BASE_URL}/_DSF6213.JPG` },
  { source: `${BASE_URL}/_DSF6214.JPG` },
  { source: `${BASE_URL}/_DSF6215.JPG` },
  { source: `${BASE_URL}/_DSF6216.JPG` },
  { source: `${BASE_URL}/_DSF6217.JPG` },
  { source: `${BASE_URL}/_DSF6219.JPG` },
  { source: `${BASE_URL}/_DSF6220.JPG` },
  { source: `${BASE_URL}/_DSF6223.JPG` },
  { source: `${BASE_URL}/_DSF6224.JPG` },
  { source: `${BASE_URL}/_DSF6225.JPG` },
  { source: `${BASE_URL}/_DSF6226.JPG` },
  { source: `${BASE_URL}/_DSF6227.JPG` },
  { source: `${BASE_URL}/_DSF6228.JPG` },
  { source: `${BASE_URL}/_DSF6229.JPG` },
  { source: `${BASE_URL}/_DSF6231.JPG` },
  { source: `${BASE_URL}/_DSF6232.JPG` },
  { source: `${BASE_URL}/_DSF6233.JPG` },
  { source: `${BASE_URL}/_DSF6234.JPG` },
  { source: `${BASE_URL}/_DSF6235.JPG` },
  { source: `${BASE_URL}/_DSF6236.JPG` },
  { source: `${BASE_URL}/_DSF6237.JPG` },
  { source: `${BASE_URL}/_DSF6238.JPG` },
  { source: `${BASE_URL}/_DSF6239.JPG` },
  { source: `${BASE_URL}/_DSF6241.JPG` },
  { source: `${BASE_URL}/_DSF6242.JPG` },
  { source: `${BASE_URL}/_DSF6243.JPG` },
  { source: `${BASE_URL}/_DSF6244.JPG` },
  { source: `${BASE_URL}/_DSF6245.JPG` },
  { source: `${BASE_URL}/_DSF6246.JPG` },
  { source: `${BASE_URL}/_DSF6247.JPG` },
  { source: `${BASE_URL}/_DSF6248.JPG` },
  { source: `${BASE_URL}/_DSF6249.JPG` },
  { source: `${BASE_URL}/_DSF6250.JPG` },
  { source: `${BASE_URL}/_DSF6251.JPG` },
  { source: `${BASE_URL}/_DSF6255.JPG` },
  { source: `${BASE_URL}/_DSF6256.JPG` },
  { source: `${BASE_URL}/_DSF6257.JPG` },
  { source: `${BASE_URL}/_DSF6258.JPG` },
  { source: `${BASE_URL}/_DSF6259.JPG` },
  { source: `${BASE_URL}/_DSF6260.JPG` },
  { source: `${BASE_URL}/_DSF6261.JPG` },
  { source: `${BASE_URL}/_DSF6262.JPG` },
  { source: `${BASE_URL}/_DSF6263.JPG` },
  { source: `${BASE_URL}/_DSF6264.JPG` },
  { source: `${BASE_URL}/_DSF6265.JPG` },
  { source: `${BASE_URL}/_DSF6266.JPG` },
  { source: `${BASE_URL}/_DSF6267.JPG` },
  { source: `${BASE_URL}/_DSF6268.JPG` },
  { source: `${BASE_URL}/_DSF6270.JPG` },
  { source: `${BASE_URL}/_DSF6271.JPG` },
  { source: `${BASE_URL}/_DSF6272.JPG` },
  { source: `${BASE_URL}/_DSF6273.JPG` },
  { source: `${BASE_URL}/_DSF6274.JPG` },
  { source: `${BASE_URL}/_DSF6275.JPG` },
  { source: `${BASE_URL}/_DSF6276.JPG` },
  { source: `${BASE_URL}/_DSF6277.JPG` },
  { source: `${BASE_URL}/_DSF6279.JPG` },
  { source: `${BASE_URL}/_DSF6284.JPG` },
  { source: `${BASE_URL}/_DSF6285.JPG` },
  { source: `${BASE_URL}/_DSF6286.JPG` },
  { source: `${BASE_URL}/_DSF6288.JPG` },
  { source: `${BASE_URL}/_DSF6291.JPG` },
  { source: `${BASE_URL}/_DSF6292.JPG` },
  { source: `${BASE_URL}/_DSF6293.JPG` },
  { source: `${BASE_URL}/_DSF6294.JPG` },
  { source: `${BASE_URL}/_DSF6296.JPG` },
  { source: `${BASE_URL}/_DSF6297.JPG` },
  { source: `${BASE_URL}/_DSF6298.JPG` },
  { source: `${BASE_URL}/_DSF6299.JPG` },
  { source: `${BASE_URL}/_DSF6300.JPG` },
  { source: `${BASE_URL}/_DSF6301.JPG` },
  { source: `${BASE_URL}/_DSF6302.JPG` },
  { source: `${BASE_URL}/_DSF6303.JPG` },
  { source: `${BASE_URL}/_DSF6304.JPG` },
  { source: `${BASE_URL}/_DSF6305.JPG` },
  { source: `${BASE_URL}/_DSF6307.JPG` },
  { source: `${BASE_URL}/_DSF6308.JPG` },
  { source: `${BASE_URL}/_DSF6309.JPG` },
  { source: `${BASE_URL}/_DSF6310.JPG` },
  { source: `${BASE_URL}/_DSF6312.JPG` },
  { source: `${BASE_URL}/_DSF6313.JPG` },
]

const setting = {
    width: '350px',
    height: ['500px', '170px'],
    layout: [1, 2],
    photos: PHOTO_LIST,
    showNumOfRemainingPhotos: true
};


function App() {
  return (
    <div className="App">
      <header className="App-header">
        <ReactPhotoCollage {...setting} />
      </header>
    </div>
  );
}

export default App;
